"""
SAT-SA Rule Intelligence Engine.

This module contains deterministic, explainable rules used by
the supervisory intelligence layer.

Important design principle:

    Rule Engine
        ↓
    FindingSignal

Every triggered rule produces:
    - rule ID
    - category
    - severity
    - score
    - entity
    - explanation
    - evidence
    - recommended action

No machine learning is required here.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Protocol


# ============================================================================
# 1. STANDARDIZED FINDING SIGNAL
# ============================================================================


@dataclass
class FindingSignal:
    """
    Standard output produced by one intelligence rule.

    Think of this as a small report generated by a rule.
    """

    rule_id: str

    category: str

    severity: str

    score: float

    entity_type: str

    entity_id: str

    title: str

    reason: str

    evidence: dict[str, Any] = field(
        default_factory=dict
    )

    recommended_action: str = (
        "Supervisor review recommended"
    )

    confidence: str = "Medium"

    def to_dict(self) -> dict[str, Any]:
        """
        Convert the FindingSignal into a normal dictionary.

        This will later make it easy for:
            FastAPI
            JSON
            PostgreSQL
            frontend
        """

        return asdict(self)


# ============================================================================
# 2. RULE INTERFACE
# ============================================================================


class Rule(Protocol):
    """
    Every rule follows the same interface.

    A rule receives one analyst feature record and either:

        returns FindingSignal

    or:

        returns None

    if the rule does not trigger.
    """

    rule_id: str

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:
        ...


# ============================================================================
# 3. HELPER FUNCTIONS
# ============================================================================


def _number(
    value: Any,
    default: float = 0.0,
) -> float:
    """
    Safely convert a value into a number.
    """

    if value is None:
        return default

    try:
        return float(value)

    except (
        TypeError,
        ValueError,
    ):
        return default


def _integer(
    value: Any,
    default: int = 0,
) -> int:
    """
    Safely convert a value into an integer.
    """

    if value is None:
        return default

    try:
        return int(value)

    except (
        TypeError,
        ValueError,
    ):
        return default


def _confidence_from_observations(
    observations: int,
) -> str:
    """
    Estimate confidence based on the amount of data.

    This is NOT model confidence.

    It simply answers:

        "How much observed activity supports this rule?"
    """

    if observations >= 10:
        return "High"

    if observations >= 3:
        return "Medium"

    return "Low"


def _severity_from_score(
    score: float,
) -> str:
    """
    Convert a score into a severity level.
    """

    if score >= 80:
        return "CRITICAL"

    if score >= 60:
        return "HIGH"

    if score >= 40:
        return "MEDIUM"

    return "LOW"


# ============================================================================
# 4. FAST CLOSURE RULE
# ============================================================================


class FastClosureRule:
    """
    Detect unusually fast alert closure.

    Current SAT-SA baseline:

        average closure time < 10 minutes

    We require at least one closed alert.
    """

    rule_id = "FAST_CLOSURE"

    threshold_minutes = 10.0

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_alerts = _integer(
            features.get("total_alerts")
        )

        closed_alerts = _integer(
            features.get("closed_alerts")
        )

        avg_closure_time = features.get(
            "average_closure_time_minutes"
        )

        if total_alerts <= 0:
            return None

        if closed_alerts <= 0:
            return None

        if avg_closure_time is None:
            return None

        avg_closure_time = _number(
            avg_closure_time
        )

        if avg_closure_time >= self.threshold_minutes:
            return None

        observations = (
            total_alerts
            + _integer(
                features.get(
                    "total_investigations"
                )
            )
        )

        return FindingSignal(
            rule_id=self.rule_id,

            category="EXECUTION_GAP",

            severity="HIGH",

            score=30.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Suspiciously Fast Alert Closure"
            ),

            reason=(
                "The analyst's average alert closure "
                "time is below the supervisory threshold."
            ),

            evidence={
                "average_closure_time_minutes": round(
                    avg_closure_time,
                    2,
                ),

                "threshold_minutes": (
                    self.threshold_minutes
                ),

                "closed_alerts": closed_alerts,

                "total_alerts": total_alerts,
            },

            recommended_action=(
                "Review a sample of rapidly closed "
                "alerts and their investigation evidence."
            ),

            confidence=(
                _confidence_from_observations(
                    observations
                )
            ),
        )


# ============================================================================
# 5. LOW EVIDENCE RULE
# ============================================================================


class NoEvidenceRule:
    """
    Detect analysts with low evidence-review rates.

    Current threshold:

        evidence review rate < 50%

    At least one alert must exist.
    """

    rule_id = "NO_EVIDENCE"

    threshold_percent = 50.0

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_alerts = _integer(
            features.get("total_alerts")
        )

        if total_alerts <= 0:
            return None

        evidence_rate = _number(
            features.get(
                "evidence_review_rate"
            )
        )

        if evidence_rate >= self.threshold_percent:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="EXECUTION_GAP",

            severity="HIGH",

            score=20.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Low Evidence Review Rate"
            ),

            reason=(
                "A significant proportion of the "
                "analyst's alerts were closed without "
                "recorded evidence review."
            ),

            evidence={
                "evidence_review_rate": round(
                    evidence_rate,
                    2,
                ),

                "threshold_percent": (
                    self.threshold_percent
                ),

                "total_alerts": total_alerts,
            },

            recommended_action=(
                "Review alert evidence handling and "
                "investigation documentation."
            ),

            confidence=(
                _confidence_from_observations(
                    total_alerts
                )
            ),
        )


# ============================================================================
# 6. LOW ESCALATION RULE
# ============================================================================


class NoEscalationRule:
    """
    Detect unusually low escalation behavior.

    Current SAT-SA threshold:

        escalation rate < 10%

    We require at least two alerts because one alert
    is not enough evidence to infer a pattern.
    """

    rule_id = "NO_ESCALATION"

    threshold_percent = 10.0

    minimum_alerts = 2

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_alerts = _integer(
            features.get("total_alerts")
        )

        if total_alerts < self.minimum_alerts:
            return None

        escalation_rate = _number(
            features.get(
                "escalation_rate"
            )
        )

        if escalation_rate >= self.threshold_percent:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="EXECUTION_GAP",

            severity="MEDIUM",

            score=15.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Low Alert Escalation Rate"
            ),

            reason=(
                "The analyst has a low recorded "
                "escalation rate across multiple alerts."
            ),

            evidence={
                "escalation_rate": round(
                    escalation_rate,
                    2,
                ),

                "threshold_percent": (
                    self.threshold_percent
                ),

                "total_alerts": total_alerts,
            },

            recommended_action=(
                "Review whether escalation decisions "
                "are consistent with alert severity "
                "and investigation findings."
            ),

            confidence=(
                _confidence_from_observations(
                    total_alerts
                )
            ),
        )


# ============================================================================
# 7. SHALLOW INVESTIGATION RULE
# ============================================================================


class ShallowInvestigationRule:
    """
    Detect investigations with very little query activity.
    """

    rule_id = "SHALLOW_INVESTIGATION"

    threshold_queries = 2.0

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_investigations = _integer(
            features.get(
                "total_investigations"
            )
        )

        if total_investigations <= 0:
            return None

        average_queries = _number(
            features.get(
                "average_queries"
            )
        )

        if average_queries >= self.threshold_queries:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="INVESTIGATION_QUALITY",

            severity="HIGH",

            score=20.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Shallow Investigation Activity"
            ),

            reason=(
                "Investigations contain very little "
                "recorded query activity."
            ),

            evidence={
                "average_queries": round(
                    average_queries,
                    2,
                ),

                "threshold_queries": (
                    self.threshold_queries
                ),

                "total_investigations": (
                    total_investigations
                ),
            },

            recommended_action=(
                "Review investigation depth, "
                "queries performed and supporting evidence."
            ),

            confidence=(
                _confidence_from_observations(
                    total_investigations
                )
            ),
        )


# ============================================================================
# 8. SHORT NOTES RULE
# ============================================================================


class ShortNotesRule:
    """
    Detect a high rate of unusually short investigation notes.

    The analytics layer should provide:

        short_note_rate

    expressed as a percentage.
    """

    rule_id = "SHORT_NOTES"

    threshold_percent = 50.0

    minimum_investigations = 2

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_investigations = _integer(
            features.get(
                "total_investigations"
            )
        )

        if (
            total_investigations
            < self.minimum_investigations
        ):
            return None

        short_note_rate = _number(
            features.get(
                "short_note_rate"
            )
        )

        if short_note_rate <= self.threshold_percent:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="INVESTIGATION_QUALITY",

            severity="MEDIUM",

            score=15.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "High Rate of Short Investigation Notes"
            ),

            reason=(
                "A high proportion of investigations "
                "contain unusually short notes."
            ),

            evidence={
                "short_note_rate": round(
                    short_note_rate,
                    2,
                ),

                "threshold_percent": (
                    self.threshold_percent
                ),

                "total_investigations": (
                    total_investigations
                ),
            },

            recommended_action=(
                "Review investigation narratives for "
                "specificity, evidence references and conclusions."
            ),

            confidence=(
                _confidence_from_observations(
                    total_investigations
                )
            ),
        )


# ============================================================================
# 9. REPEATED NOTES RULE
# ============================================================================


class RepeatedNotesRule:
    """
    Detect repeated investigation notes.

    The analytics layer provides:

        repeated_note_rate

    as a percentage.

    This does NOT accuse an analyst of misconduct.

    It identifies a pattern requiring supervisory review.
    """

    rule_id = "REPEATED_NOTES"

    threshold_percent = 40.0

    minimum_investigations = 3

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_investigations = _integer(
            features.get(
                "total_investigations"
            )
        )

        if (
            total_investigations
            < self.minimum_investigations
        ):
            return None

        repeated_note_rate = _number(
            features.get(
                "repeated_note_rate"
            )
        )

        if repeated_note_rate <= self.threshold_percent:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="BEHAVIORAL_PATTERN",

            severity="MEDIUM",

            score=20.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Repeated Investigation Notes"
            ),

            reason=(
                "A substantial proportion of the "
                "analyst's investigation notes are repeated."
            ),

            evidence={
                "repeated_note_rate": round(
                    repeated_note_rate,
                    2,
                ),

                "threshold_percent": (
                    self.threshold_percent
                ),

                "total_investigations": (
                    total_investigations
                ),
            },

            recommended_action=(
                "Review investigation notes for "
                "case-specific reasoning and evidence."
            ),

            confidence=(
                _confidence_from_observations(
                    total_investigations
                )
            ),
        )


# ============================================================================
# 10. VERY SHORT INVESTIGATION RULE
# ============================================================================


class VeryShortInvestigationRule:
    """
    Detect unusually short investigation duration.
    """

    rule_id = "VERY_SHORT_INVESTIGATION"

    threshold_minutes = 10.0

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> FindingSignal | None:

        total_investigations = _integer(
            features.get(
                "total_investigations"
            )
        )

        if total_investigations <= 0:
            return None

        average_duration = features.get(
            "average_investigation_duration_minutes"
        )

        if average_duration is None:
            return None

        average_duration = _number(
            average_duration
        )

        if average_duration >= self.threshold_minutes:
            return None

        return FindingSignal(
            rule_id=self.rule_id,

            category="INVESTIGATION_QUALITY",

            severity="MEDIUM",

            score=15.0,

            entity_type="ANALYST",

            entity_id=str(
                features.get(
                    "analyst_id"
                )
            ),

            title=(
                "Very Short Investigations"
            ),

            reason=(
                "The analyst's average investigation "
                "duration is unusually short."
            ),

            evidence={
                "average_duration_minutes": round(
                    average_duration,
                    2,
                ),

                "threshold_minutes": (
                    self.threshold_minutes
                ),

                "total_investigations": (
                    total_investigations
                ),
            },

            recommended_action=(
                "Review investigation timelines and "
                "depth of investigative activity."
            ),

            confidence=(
                _confidence_from_observations(
                    total_investigations
                )
            ),
        )


# ============================================================================
# 11. RULE ENGINE
# ============================================================================


class RuleEngine:
    """
    Executes all deterministic intelligence rules.

    Usage:

        engine = RuleEngine()

        signals = engine.evaluate(features)

    The result is a list of FindingSignal objects.
    """

    def __init__(
        self,
        rules: list[Rule] | None = None,
    ) -> None:

        if rules is None:

            self.rules = [
                FastClosureRule(),
                NoEvidenceRule(),
                NoEscalationRule(),
                ShallowInvestigationRule(),
                ShortNotesRule(),
                RepeatedNotesRule(),
                VeryShortInvestigationRule(),
            ]

        else:

            self.rules = rules

    def evaluate(
        self,
        features: dict[str, Any],
    ) -> list[FindingSignal]:
        """
        Run every rule against one analyst.
        """

        signals: list[FindingSignal] = []

        for rule in self.rules:

            try:

                signal = rule.evaluate(
                    features
                )

            except Exception:
                # A single broken rule should not
                # crash the entire intelligence engine.
                #
                # We deliberately do not silently
                # create a finding here.
                continue

            if signal is not None:
                signals.append(signal)

        return signals

    def evaluate_many(
        self,
        feature_records: list[
            dict[str, Any]
        ],
    ) -> list[FindingSignal]:
        """
        Run all rules against many analysts.
        """

        signals: list[FindingSignal] = []

        for features in feature_records:

            signals.extend(
                self.evaluate(
                    features
                )
            )

        return signals

    def calculate_score(
        self,
        signals: list[FindingSignal],
    ) -> float:
        """
        Combine triggered rule scores.

        The score is capped at 100.

        Example:

            30 + 20 + 15 = 65
        """

        total = sum(
            signal.score
            for signal in signals
        )

        return round(
            min(
                total,
                100.0,
            ),
            2,
        )

    def severity(
        self,
        signals: list[FindingSignal],
    ) -> str:
        """
        Determine overall severity from triggered rules.
        """

        if not signals:
            return "LOW"

        severity_order = {
            "LOW": 1,
            "MEDIUM": 2,
            "HIGH": 3,
            "CRITICAL": 4,
        }

        highest = max(
            signals,
            key=lambda signal: severity_order.get(
                signal.severity,
                0,
            ),
        )

        return highest.severity

    def summary(
        self,
        features: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Produce a compact summary for one analyst.

        This is useful for the analytics layer and
        later for the Risk Engine.
        """

        signals = self.evaluate(
            features
        )

        score = self.calculate_score(
            signals
        )

        severity = self.severity(
            signals
        )

        observations = (
            _integer(
                features.get(
                    "total_alerts"
                )
            )
            + _integer(
                features.get(
                    "total_investigations"
                )
            )
        )

        confidence = (
            _confidence_from_observations(
                observations
            )
        )

        return {
            "score": score,

            "severity": severity,

            "confidence": confidence,

            "triggered_rules": [
                signal.rule_id
                for signal in signals
            ],

            "indicators": [
                signal.title
                for signal in signals
            ],

            "signals": [
                signal.to_dict()
                for signal in signals
            ],
        }


# ============================================================================
# 12. SIMPLE PUBLIC FUNCTION
# ============================================================================


def evaluate_rules(
    features: dict[str, Any],
) -> dict[str, Any]:
    """
    Convenience function.

    This is useful when another part of SAT-SA simply wants:

        rule_result = evaluate_rules(features)
    """

    engine = RuleEngine()

    return engine.summary(
        features
    )