import { useMemo, useRef, useState } from "react";
import type { ChangeEvent } from "react";
import {
  Database,
  Upload,
  CheckCircle2,
  AlertCircle,
  Clock3,
  FileText,
  Eye,
  X,
  ShieldCheck,
  BarChart3,
} from "lucide-react";

interface DatasetDefinition {
  key: string;
  filename: string;
  label: string;
  description: string;
  idColumn: string;
  idPrefix: string;
  columns: string[];
  required: string[];
  records: number;
  lastUpdated: string;
  status: "Ready" | "Needs Attention" | "Not Uploaded";
}

interface DatasetHistory {
  id: number;
  filename: string;
  dataset: string;
  uploadedAt: string;
  records: number;
  status: "Completed" | "Failed" | "Processing";
  message: string;
}

interface ValidationResult {
  filename: string;
  dataset: string;
  passed: boolean;
  rows: number;
  missingColumns: string[];
  message: string;
}

const datasetDefinitions: DatasetDefinition[] = [
  {
    key: "organizations",
    filename: "organizations.csv",
    label: "Organizations",
    description:
      "Organization master data used for multi-organization support, risk assessment and peer benchmarking.",
    idColumn: "organization_id",
    idPrefix: "ORG",
    columns: [
      "organization_id",
      "organization_name",
      "industry",
      "organization_size",
      "soc_maturity",
      "region",
      "created_at",
    ],
    required: [
      "organization_id",
      "organization_name",
    ],
    records: 52,
    lastUpdated: "Today, 09:42",
    status: "Ready",
  },

  {
    key: "analysts",
    filename: "analysts.csv",
    label: "Analysts",
    description:
      "SOC analyst information used for analyst performance and workload analysis.",
    idColumn: "analyst_id",
    idPrefix: "AN",
    columns: [
      "analyst_id",
      "organization_id",
      "name",
      "role",
      "team",
      "experience_years",
      "shift",
      "status",
      "joined_at",
    ],
    required: [
      "analyst_id",
      "organization_id",
      "name",
    ],
    records: 326,
    lastUpdated: "Today, 09:38",
    status: "Ready",
  },

  {
    key: "assets",
    filename: "assets.csv",
    label: "Assets",
    description:
      "IT infrastructure monitored by the SOC including criticality, environment and status.",
    idColumn: "asset_id",
    idPrefix: "AST",
    columns: [
      "asset_id",
      "organization_id",
      "asset_identifier",
      "asset_name",
      "asset_type",
      "criticality",
      "environment",
      "location",
      "status",
    ],
    required: [
      "asset_id",
      "organization_id",
      "asset_identifier",
      "asset_name",
    ],
    records: 8920,
    lastUpdated: "Today, 09:35",
    status: "Ready",
  },

  {
    key: "alerts",
    filename: "alerts.csv",
    label: "Alerts",
    description:
      "Security alerts generated by SIEM and security tools for SOC handling analysis.",
    idColumn: "alert_id",
    idPrefix: "ALT",
    columns: [
      "alert_id",
      "external_id",
      "organization_id",
      "asset_id",
      "analyst_id",
      "alert_type",
      "severity",
      "status",
      "created_at",
      "closed_at",
      "closure_time_minutes",
      "investigation_notes",
      "evidence_reviewed",
      "escalated",
      "false_positive",
      "incident_id",
    ],
    required: [
      "alert_id",
      "external_id",
      "organization_id",
      "asset_id",
      "alert_type",
      "severity",
      "status",
      "created_at",
    ],
    records: 125400,
    lastUpdated: "Today, 09:30",
    status: "Ready",
  },

  {
    key: "investigations",
    filename: "investigations.csv",
    label: "Investigations",
    description:
      "Investigation activities performed by analysts for security alerts.",
    idColumn: "investigation_id",
    idPrefix: "INV",
    columns: [
      "investigation_id",
      "alert_id",
      "analyst_id",
      "started_at",
      "completed_at",
      "duration_minutes",
      "actions_performed",
      "queries_executed",
      "evidence_reviewed",
      "investigation_notes",
      "findings",
      "escalation_decision",
    ],
    required: [
      "investigation_id",
      "alert_id",
      "analyst_id",
      "started_at",
    ],
    records: 24300,
    lastUpdated: "Today, 09:26",
    status: "Ready",
  },

  {
    key: "incidents",
    filename: "incidents.csv",
    label: "Incidents",
    description:
      "Confirmed security incidents associated with organizations and alerts.",
    idColumn: "incident_id",
    idPrefix: "INC",
    columns: [
      "incident_id",
      "external_id",
      "organization_id",
      "title",
      "severity",
      "status",
      "description",
      "created_at",
      "resolved_at",
    ],
    required: [
      "incident_id",
      "external_id",
      "organization_id",
      "title",
      "created_at",
    ],
    records: 4860,
    lastUpdated: "Today, 09:21",
    status: "Ready",
  },

  {
    key: "asset_activity",
    filename: "asset_activity.csv",
    label: "Asset Activity",
    description:
      "Normal activity generated by monitored assets for baseline and anomaly analysis.",
    idColumn: "activity_id",
    idPrefix: "ACT",
    columns: [
      "activity_id",
      "asset_id",
      "timestamp",
      "event_count",
      "log_sources_active",
      "network_events",
      "authentication_events",
      "status",
    ],
    required: [
      "activity_id",
      "asset_id",
      "timestamp",
    ],
    records: 184500,
    lastUpdated: "Today, 09:15",
    status: "Ready",
  },

  {
    key: "peer_benchmarks",
    filename: "peer_benchmarks.csv",
    label: "Peer Benchmarks",
    description:
      "Benchmark metrics used to compare organization SOC performance against peers.",
    idColumn: "benchmark_id",
    idPrefix: "BENCH",
    columns: [
      "benchmark_id",
      "organization_id",
      "metric_name",
      "metric_value",
      "peer_mean",
      "peer_stddev",
      "benchmark_period",
      "calculated_at",
    ],
    required: [
      "benchmark_id",
      "organization_id",
      "metric_name",
      "benchmark_period",
      "calculated_at",
    ],
    records: 3640,
    lastUpdated: "Today, 09:10",
    status: "Ready",
  },
];

const initialHistory: DatasetHistory[] = [
  {
    id: 1,
    filename: "alerts.csv",
    dataset: "Alerts",
    uploadedAt: "Today, 09:30",
    records: 125400,
    status: "Completed",
    message: "Validation passed successfully.",
  },
  {
    id: 2,
    filename: "investigations.csv",
    dataset: "Investigations",
    uploadedAt: "Today, 09:26",
    records: 24300,
    status: "Completed",
    message: "Validation passed successfully.",
  },
  {
    id: 3,
    filename: "asset_activity.csv",
    dataset: "Asset Activity",
    uploadedAt: "Today, 09:15",
    records: 184500,
    status: "Completed",
    message: "Validation passed successfully.",
  },
  {
    id: 4,
    filename: "organizations.csv",
    dataset: "Organizations",
    uploadedAt: "Yesterday, 18:42",
    records: 52,
    status: "Completed",
    message: "Validation passed successfully.",
  },
];

function formatNumber(value: number) {
  return new Intl.NumberFormat("en-IN").format(value);
}

function DataManagement() {
  const fileInputRef = useRef<HTMLInputElement | null>(null);

  const [datasets, setDatasets] =
    useState<DatasetDefinition[]>(datasetDefinitions);

  const [history, setHistory] =
    useState<DatasetHistory[]>(initialHistory);

  const [selectedDataset, setSelectedDataset] =
    useState<DatasetDefinition | null>(null);

  const [validationResult, setValidationResult] =
    useState<ValidationResult | null>(null);

  const [search, setSearch] = useState("");

  const [historyFilter, setHistoryFilter] =
    useState("All");

  const [uploadingDataset, setUploadingDataset] =
    useState<DatasetDefinition | null>(null);

  // =========================
  // FILTER DATASETS
  // =========================

  const filteredDatasets = useMemo(() => {
    const value = search.toLowerCase().trim();

    if (!value) {
      return datasets;
    }

    return datasets.filter(
      (dataset) =>
        dataset.label.toLowerCase().includes(value) ||
        dataset.filename.toLowerCase().includes(value)
    );
  }, [datasets, search]);

  // =========================
  // FILTER HISTORY
  // =========================

  const filteredHistory = useMemo(() => {
    if (historyFilter === "All") {
      return history;
    }

    return history.filter(
      (item) => item.status === historyFilter
    );
  }, [history, historyFilter]);

  // =========================
  // STATISTICS
  // =========================

  const totalRecords = datasets.reduce(
    (total, dataset) => total + dataset.records,
    0
  );

  const readyDatasets = datasets.filter(
    (dataset) => dataset.status === "Ready"
  ).length;

  const attentionDatasets = datasets.filter(
    (dataset) => dataset.status === "Needs Attention"
  ).length;

  // =========================
  // OPEN FILE PICKER
  // =========================

  const handleUploadClick = (
    dataset: DatasetDefinition
  ) => {
    setUploadingDataset(dataset);

    setTimeout(() => {
      fileInputRef.current?.click();
    }, 50);
  };

  // =========================
  // VALIDATE CSV HEADER
  // =========================

  const handleFileChange = (
    event: ChangeEvent<HTMLInputElement>
  ) => {
    const file = event.target.files?.[0];

    if (!file || !uploadingDataset) {
      return;
    }

    if (!file.name.toLowerCase().endsWith(".csv")) {
      setValidationResult({
        filename: file.name,
        dataset: uploadingDataset.label,
        passed: false,
        rows: 0,
        missingColumns: [],
        message: "Only CSV files are supported.",
      });

      setUploadingDataset(null);

      event.target.value = "";

      return;
    }

    const reader = new FileReader();

    reader.onload = () => {
      const text = String(reader.result || "");

      const firstLine = text.split(/\r?\n/)[0];

      const headers = firstLine
        .split(",")
        .map((header) =>
          header.trim().replace(/^"|"$/g, "")
        )
        .filter(Boolean);

      const missingColumns =
        uploadingDataset.columns.filter(
          (column) => !headers.includes(column)
        );

      const rows = Math.max(
        0,
        text.split(/\r?\n/).filter((line) => line.trim()).length - 1
      );

      const passed = missingColumns.length === 0;

      setValidationResult({
        filename: file.name,
        dataset: uploadingDataset.label,
        passed,
        rows,
        missingColumns,
        message: passed
          ? "CSV header structure matches the expected dataset schema."
          : "The uploaded CSV is missing one or more required dataset columns.",
      });

      if (passed) {
        setDatasets((current) =>
          current.map((dataset) =>
            dataset.key === uploadingDataset.key
              ? {
                  ...dataset,
                  records: rows,
                  lastUpdated: "Just now",
                  status: "Ready",
                }
              : dataset
          )
        );

        setHistory((current) => [
          {
            id: Date.now(),
            filename: file.name,
            dataset: uploadingDataset.label,
            uploadedAt: "Just now",
            records: rows,
            status: "Completed",
            message:
              "Frontend validation passed. Backend ingestion is pending API integration.",
          },
          ...current,
        ]);
      }

      setUploadingDataset(null);
      event.target.value = "";
    };

    reader.onerror = () => {
      setValidationResult({
        filename: file.name,
        dataset: uploadingDataset.label,
        passed: false,
        rows: 0,
        missingColumns: [],
        message: "Unable to read the selected CSV file.",
      });

      setUploadingDataset(null);
      event.target.value = "";
    };

    reader.readAsText(file);
  };

  return (
    <div className="data-management-page">

      {/* =========================
          PAGE HEADER
      ========================= */}

      <div className="page-heading">
        <div>
          <h2>Data Management</h2>

          <p>
            Manage SAT-SA datasets, validate CSV structures and
            monitor data ingestion.
          </p>
        </div>
      </div>

      {/* Hidden file input */}

      <input
        ref={fileInputRef}
        type="file"
        accept=".csv,text/csv"
        style={{ display: "none" }}
        onChange={handleFileChange}
      />

      {/* =========================
          OVERVIEW CARDS
      ========================= */}

      <div className="data-summary">

        <div className="data-summary-card">
          <div className="data-summary-icon">
            <Database size={21} />
          </div>

          <div>
            <span>Total Datasets</span>
            <strong>{datasets.length}</strong>
            <small>Supported CSV sources</small>
          </div>
        </div>

        <div className="data-summary-card">
          <div className="data-summary-icon success">
            <CheckCircle2 size={21} />
          </div>

          <div>
            <span>Ready</span>
            <strong>{readyDatasets}</strong>
            <small>Datasets available</small>
          </div>
        </div>

        <div className="data-summary-card">
          <div className="data-summary-icon warning">
            <AlertCircle size={21} />
          </div>

          <div>
            <span>Needs Attention</span>
            <strong>{attentionDatasets}</strong>
            <small>Validation issues</small>
          </div>
        </div>

        <div className="data-summary-card">
          <div className="data-summary-icon">
            <BarChart3 size={21} />
          </div>

          <div>
            <span>Total Records</span>
            <strong>{formatNumber(totalRecords)}</strong>
            <small>Across all datasets</small>
          </div>
        </div>

      </div>

      {/* =========================
          DATASET SECTION
      ========================= */}

      <div className="data-panel">

        <div className="data-panel-header">

          <div>
            <h3>Available Datasets</h3>

            <p>
              Dataset schemas are aligned with the SAT-SA
              ingestion pipeline.
            </p>
          </div>

          <div className="data-search">

            <Database size={17} />

            <input
              type="text"
              placeholder="Search datasets..."
              value={search}
              onChange={(event) =>
                setSearch(event.target.value)
              }
            />

          </div>

        </div>

        {/* =========================
            DATASET TABLE
        ========================= */}

        <div className="table-container">

          <table className="organizations-table">

            <thead>
              <tr>
                <th>Dataset</th>
                <th>Records</th>
                <th>ID Field</th>
                <th>Required Fields</th>
                <th>Status</th>
                <th>Last Updated</th>
                <th>Actions</th>
              </tr>
            </thead>

            <tbody>

              {filteredDatasets.map((dataset) => (

                <tr key={dataset.key}>

                  <td>
                    <div className="organization-name">

                      <div className="organization-logo">
                        <FileText size={18} />
                      </div>

                      <div>
                        <strong>
                          {dataset.label}
                        </strong>

                        <span>
                          {dataset.filename}
                        </span>
                      </div>

                    </div>
                  </td>

                  <td>
                    {formatNumber(dataset.records)}
                  </td>

                  <td>
                    <div className="dataset-field">

                      <strong>
                        {dataset.idColumn}
                      </strong>

                      <span>
                        Prefix: {dataset.idPrefix}
                      </span>

                    </div>
                  </td>

                  <td>
                    <span className="field-count">
                      {dataset.required.length} required
                    </span>
                  </td>

                  <td>

                    <span
                      className={`status-badge ${
                        dataset.status === "Ready"
                          ? "active"
                          : dataset.status ===
                            "Needs Attention"
                          ? "warning"
                          : "inactive"
                      }`}
                    >
                      {dataset.status}
                    </span>

                  </td>

                  <td>
                    {dataset.lastUpdated}
                  </td>

                  <td>

                    <div className="table-actions">

                      <button
                        title="View Dataset"
                        onClick={() =>
                          setSelectedDataset(dataset)
                        }
                      >
                        <Eye size={17} />
                      </button>

                      <button
                        title="Upload CSV"
                        onClick={() =>
                          handleUploadClick(dataset)
                        }
                      >
                        <Upload size={17} />
                      </button>

                    </div>

                  </td>

                </tr>

              ))}

              {filteredDatasets.length === 0 && (
                <tr>
                  <td
                    colSpan={7}
                    className="empty-table"
                  >
                    No datasets found.
                  </td>
                </tr>
              )}

            </tbody>

          </table>

        </div>

      </div>

      {/* =========================
          DATASET HISTORY
      ========================= */}

      <div className="data-panel">

        <div className="data-panel-header">

          <div>
            <h3>Dataset History</h3>

            <p>
              Recent dataset uploads and validation results.
            </p>
          </div>

          <select
            className="data-history-filter"
            value={historyFilter}
            onChange={(event) =>
              setHistoryFilter(event.target.value)
            }
          >
            <option>All</option>
            <option>Completed</option>
            <option>Processing</option>
            <option>Failed</option>
          </select>

        </div>

        <div className="table-container">

          <table className="organizations-table">

            <thead>
              <tr>
                <th>Dataset</th>
                <th>File</th>
                <th>Uploaded</th>
                <th>Records</th>
                <th>Status</th>
                <th>Message</th>
              </tr>
            </thead>

            <tbody>

              {filteredHistory.map((item) => (

                <tr key={item.id}>

                  <td>
                    <strong>
                      {item.dataset}
                    </strong>
                  </td>

                  <td>
                    {item.filename}
                  </td>

                  <td>
                    {item.uploadedAt}
                  </td>

                  <td>
                    {formatNumber(item.records)}
                  </td>

                  <td>

                    <span
                      className={`status-badge ${
                        item.status === "Completed"
                          ? "active"
                          : item.status === "Processing"
                          ? "warning"
                          : "inactive"
                      }`}
                    >
                      {item.status}
                    </span>

                  </td>

                  <td>
                    <span className="history-message">
                      {item.message}
                    </span>
                  </td>

                </tr>

              ))}

              {filteredHistory.length === 0 && (
                <tr>
                  <td
                    colSpan={6}
                    className="empty-table"
                  >
                    No history found.
                  </td>
                </tr>
              )}

            </tbody>

          </table>

        </div>

      </div>

      {/* =====================================================
          DATASET DETAILS MODAL
      ===================================================== */}

      {selectedDataset && (

        <div
          className="details-modal-overlay"
          onClick={() =>
            setSelectedDataset(null)
          }
        >

          <div
            className="details-modal dataset-details-modal"
            onClick={(event) =>
              event.stopPropagation()
            }
          >

            <div className="details-modal-header">

              <div>
                <h3>
                  {selectedDataset.label}
                </h3>

                <p>
                  Dataset schema and ingestion information
                </p>
              </div>

              <button
                className="details-modal-close"
                onClick={() =>
                  setSelectedDataset(null)
                }
                aria-label="Close"
              >
                <X size={18} />
              </button>

            </div>

            <div className="dataset-detail-content">

              {/* DESCRIPTION */}

              <div className="dataset-description">

                <div className="dataset-detail-icon">
                  <Database size={22} />
                </div>

                <div>
                  <h4>
                    {selectedDataset.filename}
                  </h4>

                  <p>
                    {selectedDataset.description}
                  </p>
                </div>

              </div>

              {/* DATASET STATS */}

              <div className="dataset-detail-stats">

                <div>
                  <span>Records</span>
                  <strong>
                    {formatNumber(
                      selectedDataset.records
                    )}
                  </strong>
                </div>

                <div>
                  <span>ID Column</span>
                  <strong>
                    {selectedDataset.idColumn}
                  </strong>
                </div>

                <div>
                  <span>ID Prefix</span>
                  <strong>
                    {selectedDataset.idPrefix}
                  </strong>
                </div>

                <div>
                  <span>Status</span>
                  <strong>
                    {selectedDataset.status}
                  </strong>
                </div>

              </div>

              {/* COLUMNS */}

              <div className="dataset-columns-section">

                <div className="dataset-columns-heading">

                  <div>
                    <h4>
                      Expected Columns
                    </h4>

                    <span>
                      {selectedDataset.columns.length} columns
                    </span>
                  </div>

                  <ShieldCheck size={18} />

                </div>

                <div className="dataset-columns-list">

                  {selectedDataset.columns.map(
                    (column) => (

                      <div
                        key={column}
                        className={
                          selectedDataset.required.includes(
                            column
                          )
                            ? "required-column"
                            : ""
                        }
                      >

                        <span>
                          {column}
                        </span>

                        {selectedDataset.required.includes(
                          column
                        ) && (
                          <small>
                            Required
                          </small>
                        )}

                      </div>

                    )
                  )}

                </div>

              </div>

            </div>

            <div className="details-modal-footer">

              <button
                className="secondary-button"
                onClick={() =>
                  setSelectedDataset(null)
                }
              >
                Close
              </button>

              <button
                className="primary-button"
                onClick={() => {
                  const dataset =
                    selectedDataset;

                  setSelectedDataset(null);

                  handleUploadClick(dataset);
                }}
              >
                <Upload size={16} />
                Upload CSV
              </button>

            </div>

          </div>

        </div>

      )}

      {/* =====================================================
          VALIDATION RESULT MODAL
      ===================================================== */}

      {validationResult && (

        <div
          className="details-modal-overlay"
          onClick={() =>
            setValidationResult(null)
          }
        >

          <div
            className="details-modal validation-modal"
            onClick={(event) =>
              event.stopPropagation()
            }
          >

            <div className="details-modal-header">

              <div>
                <h3>
                  CSV Validation Result
                </h3>

                <p>
                  Frontend schema validation
                </p>
              </div>

              <button
                className="details-modal-close"
                onClick={() =>
                  setValidationResult(null)
                }
                aria-label="Close"
              >
                <X size={18} />
              </button>

            </div>

            <div className="validation-content">

              <div
                className={`validation-status ${
                  validationResult.passed
                    ? "passed"
                    : "failed"
                }`}
              >

                {validationResult.passed ? (
                  <CheckCircle2 size={28} />
                ) : (
                  <AlertCircle size={28} />
                )}

                <div>

                  <strong>
                    {validationResult.passed
                      ? "Validation Passed"
                      : "Validation Failed"}
                  </strong>

                  <span>
                    {validationResult.message}
                  </span>

                </div>

              </div>

              <div className="validation-info">

                <div>
                  <span>Dataset</span>
                  <strong>
                    {validationResult.dataset}
                  </strong>
                </div>

                <div>
                  <span>File</span>
                  <strong>
                    {validationResult.filename}
                  </strong>
                </div>

                <div>
                  <span>Detected Records</span>
                  <strong>
                    {formatNumber(
                      validationResult.rows
                    )}
                  </strong>
                </div>

              </div>

              {validationResult.missingColumns.length >
                0 && (

                <div className="missing-columns">

                  <h4>
                    Missing Columns
                  </h4>

                  <div>

                    {validationResult.missingColumns.map(
                      (column) => (
                        <span key={column}>
                          {column}
                        </span>
                      )
                    )}

                  </div>

                </div>

              )}

              {validationResult.passed && (

                <div className="validation-note">
                  <Clock3 size={16} />

                  <span>
                    File structure is valid for this
                    dataset. Actual PostgreSQL ingestion
                    will be connected when the backend
                    ingestion API is available.
                  </span>
                </div>

              )}

            </div>

            <div className="details-modal-footer">

              <button
                className="secondary-button"
                onClick={() =>
                  setValidationResult(null)
                }
              >
                Close
              </button>

            </div>

          </div>

        </div>

      )}

    </div>
  );
}

export default DataManagement;